#' Fitting shared frailty models wiht the EM algorithm
#'
#' @importFrom survival Surv
#' @importFrom stats approx coef model.frame model.matrix pchisq printCoefmat
#' @importFrom magrittr "%>%"
#' @useDynLib frailtoys
#' @include em_fit.R
#' @include emfrail_aux.R
#'
#' @param .data A data frame in which the formula argument can be evaluated
#' @param .formula A formula that contains on the left hand side an object of the type \code{Surv} in the Andersen-Gill format, and on the right hand side a \code{+cluster(id)} statement
#' @param .distribution (optional) An object as created by \code{\link{emfrail_distribution}} which defines the frailty distribution. See Details.
#' @param .control (optional) An object as created by \code{\link{emfrail_control}}
#'
#' @return An emfrail-type object, containing a lot of interesting information.
#' @export
#'
#' @details The \code{emfrail} function fits shared frailty models for processes which have intensity
#' \deqn{\lambda(t) = z \lambda_0(t) \exp(\gamma' \mathbf{x})}
#' with a non-parametric (Breslow) baseline intensity \eqn{\lambda_0(t)}.
#' The distribution of \eqn{z} is described by one parameter \eqn{\theta} (see the vignette on the available parametrizations).
#'
#' The "inner" problem is that, for a fixed \eqn{\theta}, the log-likelihood \eqn{l_\theta} must be maximized with respect to
#' \eqn{\lambda_0(t)} and \eqn{\gamma}. This is done via an EM algorithm, which relies in the M step on the \code{agreg} function from the \code{survival} package.
#' From this EM algorithm, standard errors are obtained using Louis' formula.
#' The "outer" problem is that of maximizing \eqn{l_\theta} with respect to \eqn{\theta}. That is done using the \code{optimx} function
#' from the \code{optimx} package, which also provides the corresponding Hessian matrix.
#' Several options exist, for example, to not do the outer loop and just maximize \eqn{l_\theta} for fixed \eqn{\theta}.
#'
#' The frailty distribution is determined by the \code{.distribution} argument. This must be generated by a call from
#' \code{emfrail_distribution()}.
#'
#' The family of supported distributions can be one of gamma, positive stable or PVF (power-variance-family).
#'
#'
#' @examples
#' dat <- survival::rats
#' m1 <- emfrail(.data =  dat, .formula = Surv(rep(0, nrow(dat)), time, status) ~  rx + sex + cluster(litter),
#' .distribution = emfrail_distribution(dist = "gamma"))
#' m1
#'
#' m2 <- emfrail(.data =  dat, .formula = Surv(rep(0, nrow(dat)), time, status) ~  rx + sex + cluster(litter),
#'               .distribution = emfrail_distribution(dist = "pvf"))
#' m2
#'
#' m3 <- emfrail(.data =  dat, .formula = Surv(rep(0, nrow(dat)), time, status) ~  rx + sex + cluster(litter),
#'               .distribution = emfrail_distribution(dist = "stable"),
#'               .control = emfrail_control(verbose = FALSE))
#' m3
#'
#'
#'
#'
#' # draw the profile likelihood for different values of the frailty variance (gamma frailty)
#' fr_var <- c(0.001, 0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
#' prof_lik <- sapply(1/fr_var, function(th)
#'   -emfrail(.data =  dat, .formula = Surv(rep(0, nrow(dat)), time, status) ~  rx + sex + cluster(litter),
#'            .distribution = emfrail_distribution(frailtypar = th), .control = emfrail_control(opt_fit = FALSE))
#' )
#'
#' plot(fr_var, prof_lik, xlab = "frailty variance", ylab = "log-likelihood")
#'
#' # check with coxph:
#' prof_lik_cph <- sapply(fr_var, function(th)
#'   survival::coxph(data =  dat, formula = Surv(rep(0, nrow(dat)), time, status) ~ rx + sex + frailty(litter, theta = th),
#'                  method = "breslow")$history[[1]][[3]])
#'
#' lines(fr_var, prof_lik_cph, col = 2)
#'
#'
#' # simulated data ----------------------------------------------------------
#' set.seed(1)
#' x <- sample(c(0,1), 300, TRUE)
#' z <- rep(rgamma(100, 1, 1), each = 3)
#'
#' time <- rexp(300, rate = z * exp(0.5*x) )
#'
#' censtime <- 5
#' status <- rep(1, 300)
#'
#' status[time >= censtime] <- 0
#' time[status == 0] <- censtime
#' time0 <- rep(0, 300)
#'
#' dd <- data.frame(id = rep(1:100, each = 3), x = x, time0 = time0, time = time, status = status)
#'
#'
#' emfrail(.data =  dd, .formula = Surv(rep(0, nrow(dat)), time, status) ~  x + cluster(id),
#'         .distribution = emfrail_distribution( dist = "stable"),
#'         .control = emfrail_control(opt_fit = TRUE))
#'
#'
#' #Recurrent events --------------------------------------------------------
#'
#' data("bladder")
#' coxph(Surv(start, stop, status) ~ treatment + frailty(id), data = bladder1, method = "breslow")
#' mod2 <- emfrail(bladder1, Surv(start, stop, status) ~ treatment + cluster(id))
#'
#' # Plotting the baseline cumulative hazard / intensity
#'
#' with(mod2$res$haz,
#'      plot(time, cumhaz, type = "s", ylim = c(0, max(cumhaz) + 2 * max(se_chz_adj)),
#'      main = "Cumulative baseline hazard",
#'      ylab = "H0"))
#' with(mod2$res$haz, lines(time, cumhaz - 1.96*se_chz, col = 2))
#' with(mod2$res$haz, lines(time, cumhaz + 1.96*se_chz, col = 2))
#' with(mod2$res$haz, lines(time, cumhaz - 1.96*se_chz_adj, col = 3, lty = 2))
#' with(mod2$res$haz, lines(time, cumhaz + 1.96*se_chz_adj, col = 3, lty = 2))
#' legend(x = 0, y = 5, legend = c("95% CI", "adjusted 95% CI"), col = c(2,3), lty = c(1,2))
#'
#' # with ggplot2
#' library(ggplot2)
#' ggplot(mod2$res$haz, aes(x = time)) +
#' geom_ribbon(aes(ymin = cumhaz - 1.96*se_chz, ymax = cumhaz + 1.96*se_chz),  fill = "grey70") +
#'   geom_ribbon(aes(ymin = cumhaz - 1.96*se_chz_adj, ymax = cumhaz + 1.96*se_chz_adj),  fill = "pink", alpha = 0.2) +
#'   geom_step(aes(y = cumhaz)) +
#'   ggtitle("Cumulative baseline hazard") +
#'   ylab("H0")
emfrail <- function(.data, .formula,
                    .distribution = emfrail_distribution(),
                    .control = emfrail_control()) {

  if(!inherits(.distribution, "emfrail_distribution"))
    stop(".distribution argument misspecified; see ?emfrail_distribution()")

  if(!inherits(.control, "emfrail_control"))
    stop(".control argument misspecified; see ?emfrail_control()")

  Call <- match.call()


  if(missing(.formula)  | missing(.data)) stop("Missing arguments")
  # if(missing(.distribution)) {
  #   .distribution <-  emfrail_distribution()
  #   print("default distribution")
  # }
  # if(missing(.control)) .control <- emfrail_control()

  cluster <- function(x) x
  mf <- model.frame(.formula, .data)

  # Identify the cluster and the ID column
  pos_cluster <- grep("cluster", names(mf))
  if(length(pos_cluster) != 1) stop("misspecified or non-specified cluster")
  id <- mf[[pos_cluster]]

  # Identify Surv object
  Y <- mf[[1]]
  if(!inherits(Y, "Surv")) stop("left hand side not a survival object")
  if(attr(Y, "type") != "counting") stop("use Surv(tstart, tstop, status)")



  nev_id <- tapply(Y[,3], id, sum)


  # get the model matrix
  X1 <- model.matrix(.formula, .data)
  # this is necessary because when factors have more levels, pos_cluster doesn't correspond any more
  pos_cluster_X1 <- grep("cluster", colnames(X1))
  X <- X1[,-c(1, pos_cluster_X1), drop=FALSE]
  # note: X has no attributes, in coxph it does.


  # some stuff for creating the C vector, is used all along.

  mcox <- survival::agreg.fit(x = X, y = Y, strata = NULL, offset = NULL, init = NULL,
                              control = survival::coxph.control(), weights = NULL, method = "breslow", rownames = NULL)

  # the "baseline" case // this will stay constant
  x2 <- matrix(rep(0, ncol(X)), nrow = 1, dimnames = list(123, dimnames(X)[[2]]))
  x2 <- scale(x2, center = mcox$means, scale = FALSE)


  # this is a fake tstart tstop with the indices in the total time points
  # Yfake <- cbind(match(Y[,1], all_times), match(Y[,2], all_times), Y[,3])



  # first time - no offset M step


  # we have: exp(linear predictors)
  # do we need this? this actually has everything centered...


  explp <- exp(mcox$linear.predictors)

  newrisk <- exp(c(x2 %*% mcox$coefficients) + 0)

  hh <- getchz(Y = Y, newrisk = newrisk, explp = explp)
  cumhaz_line <- sapply(X = apply(as.matrix(Y[,c(1,2)]), 1, as.list),
                        FUN = function(x)  sum(hh$haz_tev[x$start <= hh$tev & hh$tev <= x$stop])) *
    exp(mcox$coefficients %*% t(X))

  basehaz_line <- hh$haz_tev[match(Y[,2], hh$tev)]

  Cvec <- tapply(X = cumhaz_line,
                 INDEX = id,
                 FUN = sum)




  # a fit just for the log-likelihood;
  if(!isTRUE(.control$opt_fit)) {
    return(em_fit(logfrailtypar = log(.distribution$frailtypar),
           dist = .distribution$dist, pvfm = .distribution$pvfm,
           Y = Y, Xmat = X, id = id, nev_id = nev_id, newrisk = newrisk, basehaz_line = basehaz_line,
           mcox = list(coefficients = mcox$coefficients), explp = explp, Cvec = Cvec,
           .control = .control))
  }


  # otherwise, the maximizer
  opt_object <- optimx::optimx(par = log(.distribution$frailtypar), fn = em_fit,
               hessian = TRUE,
               #lower = -10000, upper = 10000,
               method = .control$opt_control$method, #control = .control$opt_control$control,
               dist = .distribution$dist, pvfm = .distribution$pvfm,
               Y = Y, Xmat = X, id = id, nev_id = nev_id, newrisk = newrisk, basehaz_line = basehaz_line,
               mcox = list(coefficients = mcox$coefficients), explp = explp, Cvec = Cvec,
               .control = .control)






  final_fit <- em_fit(logfrailtypar = opt_object$p1,
                dist = .distribution$dist, pvfm = .distribution$pvfm,
                Y = Y, Xmat = X, id = id, nev_id = nev_id, newrisk = newrisk, basehaz_line = basehaz_line,
                mcox = list(coefficients = mcox$coefficients), explp = explp, Cvec = Cvec,
                .control = .control, return_loglik = FALSE)

  # that the hessian
  h <- as.numeric(sqrt(1/(attr(opt_object, "details")[[3]]))/2)


  final_fit_minus <- em_fit(logfrailtypar = opt_object$p1 - h,
                      dist = .distribution$dist, pvfm = .distribution$pvfm,
                      Y = Y, Xmat = X, id = id, nev_id = nev_id, newrisk = newrisk, basehaz_line = basehaz_line,
                      mcox = list(coefficients = mcox$coefficients), explp = explp, Cvec = Cvec,
                      .control = .control, return_loglik = FALSE)

  final_fit_plus <- em_fit(logfrailtypar = opt_object$p1 + h,
                            dist = .distribution$dist, pvfm = .distribution$pvfm,
                            Y = Y, Xmat = X, id = id, nev_id = nev_id, newrisk = newrisk, basehaz_line = basehaz_line,
                            mcox = list(coefficients = mcox$coefficients), explp = explp, Cvec = Cvec,
                            .control = .control, return_loglik = FALSE)

  # instructional: this should be more or less equal to the
  # -(final_fit_plus$loglik + final_fit_minus$loglik - 2 * final_fit$loglik)/h^2

  # se_logtheta^2 / (2 * (final_fit$loglik -final_fit_plus$loglik ))

  deta_dtheta <- (c(final_fit_plus$coef, final_fit_plus$haz$haz_tev) -
    c(final_fit_minus$coef, final_fit_minus$haz$haz_tev)) / (2*h)

  #adj_se <- sqrt(diag(deta_dtheta %*% (1/(attr(opt_object, "details")[[3]])) %*% t(deta_dtheta)))


  ncoef = length(final_fit$coef)

  vcov_adj = final_fit$Vcov + deta_dtheta %*% (1/(attr(opt_object, "details")[[3]])) %*% t(deta_dtheta)

  varH <- final_fit$Vcov[(ncoef + 1): nrow(final_fit$Vcov), (ncoef+ 1): nrow(final_fit$Vcov)]
  varH_adj <- vcov_adj[(ncoef + 1): nrow(final_fit$Vcov), (ncoef+ 1): nrow(final_fit$Vcov)]

  varH_time <- numeric(nrow(varH))
  for(i in 1:nrow(varH)) {
    varH_time[i] = sum(varH[1:i, 1:i])
  }

  varH_adj_time <- numeric(nrow(varH))
  for(i in 1:nrow(varH)) {
    varH_adj_time[i] = sum(varH_adj[1:i, 1:i])
  }


res <- list(outer_m = opt_object,
              res = list(loglik = final_fit$loglik,
                         dist = final_fit$dist,
                         pvfm = final_fit$pvfm,
                         theta = final_fit$frailtypar,
                         haz = data.frame(time = final_fit$haz$tev,
                                         cumhaz = cumsum(final_fit$haz$haz_tev),
                                         se_chz = sqrt(varH_time),
                                         se_chz_adj = sqrt(varH_adj_time)),
                                          #se = final_fit$se[(1 + length(final_fit$coef)):length(final_fit$se)]),
                         z = data.frame(id = names(final_fit$Cvec),
                                        Lambda = final_fit$Cvec,
                                         z = final_fit$estep[,2] / final_fit$estep[,1]),
                                        coef = final_fit$coef,
                         se_coef = sqrt(diag(final_fit$Vcov)[seq_along(final_fit$coef)]),
                         se_coef_adj = sqrt(diag(vcov_adj)[seq_along(final_fit$coef)] )),
                   mcox = mcox,
              vcov = final_fit$Vcov,
              vcov_adj = vcov_adj
               )
  attr(res, "class") <- "emfrail"

  res


}
