# Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator token:
# 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform the E step calculations
#'
#' This is an inner wrapper for the C++ functions which perform the E step and is not made to be used by anybody ever.
#' @export
Estep <- function(c, delta, alpha, bbeta, pvfm, dist) {
    .Call("frailtoys_Estep", PACKAGE = "frailtoys", c, delta, alpha, bbeta, pvfm, dist)
}

